version: '3.7'

services:
    tf:
        image: hashicorp/terraform:0.13.3
        volumes:
        - .:/infra
        working_dir: /infra

    aws:
        image: amazon/aws-cli
        volumes:
        - .:/aws
        working_dir: /aws

